refactor: restructure with lockup dir
sablier-labs/deployments pull request #12
Opened 2024-10-08 12:23 UTC by andreivladbrg

Closes https://github.com/sablier-labs/v2-deployments/issues/10

> [!IMPORTANT]  
> The merge of this PR should be synchronized with renaming this repo to `deployments` (removing "V2") and updating the documentation in places such as [this](https://github.com/sablier-labs/docs/blob/5c96e045093887643d24eb837b4e8385abf8d177/docs/contracts/v2/02-deployments.md?plain=1#L50-L53)

2024-10-09 12:07 UTC, smol-ninja approved these changes
Renaming this repo to `deployment` can be synchronised with renaming `v2-core` to `lockup`. So, feel free to merge this and open another issue about renaming repo.

2024-10-09 12:34 UTC, andreivladbrg commented
> So, feel free to merge this and open another issue about renaming repo.

we need to also update the hyperlinks in docs

2024-10-09 14:07 UTC, smol-ninja commented
Right. So should we mark it as draft then?

2024-10-09 14:24 UTC, andreivladbrg commented
> Right. So should we mark it as draft then to prevent accidental merging of this PR

we could, but some clarifications, doesn't "draft" mean that the work for the individual PR is not finished? 
the case here is that for deployments PR is finished, but we need to updated other repos

2024-10-09 14:36 UTC, smol-ninja commented
As per https://github.blog/news-insights/product-news/introducing-draft-pull-requests/, Draft PR can be used to send various signals one of which is to block merging the pull request.

2024-12-09 07:05 UTC, smol-ninja requested changes
Here is another review after merging https://github.com/sablier-labs/v2-deployments/pull/14.

1. ZKsync broadcasts and ZKsync artifacts are missing. ZKsync artifacts should be different because of hardhat requirement (similar to lockup directory).
2. We should update the [Scripts section](https://github.com/sablier-labs/v2-deployments/tree/refactor/restructure-repo?tab=readme-ov-file#scripts) in the README file as the bash scripts are no longer used to make deployments.
3. Link to Flow npm package was missing from README which I have added in https://github.com/sablier-labs/v2-deployments/pull/12/commits/61e0b2f084871047f0b4d56bbff86e1e301a155f.

2024-12-09 07:05 UTC, smol-ninja commented on flow/v1.0.0/README.md
> +### IoTex and Tangle
We should add similar table for ZKsync as well.

2024-12-09 13:59 UTC, andreivladbrg commented
> ZKsync broadcasts 

unfortunetely i didn't have them this time, i don't know why

> ZKsync artifacts are missing

will add them

2024-12-09 14:34 UTC, smol-ninja approved these changes
LGTM.

2024-12-12 11:56 UTC, smol-ninja commented
Should we merge it @andreivladbrg given we are going live in a few hours? We will then have to update the links in docs as well.

2024-12-12 13:11 UTC, merged